# Site
title: Tijme Gommers
description: My blog about online security, privacy, hacking, programming and much more. By the way, my name is Tijme Gommers, I'm a ‎software engineer, entrepreneur and student. Programming in i.a. PHP, Java (including the Android SDK), Swift, Python and (server-side) Java/ECMA script.
keywords: blog, privacy, security, hacking, programming, tijme, gommers, development, software, finnwea
author: Tijme Gommers
language: en
language_full: english
timezone: Europe/Amsterdam
permalink: blog/:title/
permalink_defaults:

# Environments
stagings:
  production:
    url: https://finnwea.com
    root: /
  development:
    url: http://localhost
    root: /blog/public/

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 0
  order_by: -date

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 0
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: finnwea

# Plugins
html_minifier:
  enable: true
  ignore_error: false
  exclude:

# HTACCESS
include:
  - .htaccess

# RSS
feed:
  title: RSS
  type: rss2
  path: feeds/rss/rss.xml
  public_path: feeds/rss/
  limit: false
  content: false
